name: Deploy S3 Bucket
on: pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      Env: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./Terraform

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve
        working-directory: ./Terraform